name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to deploy'
        required: false
        default: 'main'

concurrency:
  group: production
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment information
        run: vercel pull --yes --environment=production \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --org-id=${{ secrets.VERCEL_ORG_ID }} \
          --project-id=${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build project
        run: vercel build --prod \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --org-id=${{ secrets.VERCEL_ORG_ID }} \
          --project-id=${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --org-id=${{ secrets.VERCEL_ORG_ID }} \
          --project-id=${{ secrets.VERCEL_PROJECT_ID }}
